### ISSUE TITLE
Webアプリケーションの設計の考え方を理解しよう

### ISSUE THREAD

**Issue by norotime** [ryokky59/comitrace#15]
画面遷移図やクラス図、ER図を作成したのちにどのように進めるか？の観点です。

1. URLを設計する
リソース（usersやblogsなど）毎にURLがどうあるべきかを考える。URLと表示されるリソースを整合させる。例えば、users/:id のURLなのに、followersやschedulesが表示されるのは変。それならば、リソースを分けてURLを users/:id/followers とすべき。URLが別れる＝コントローラが別れる。

2. コントローラを設計する
URLに紐づいて、コントローラもリソースごとに分ける。コントローラ内のアクションは、できるだけCRUDのみを記述する。scaffoldで作成されるアクション以外は、原則作らない。
コントローラにはビジネスロジックは記述しない。スカスカで良い。
銀行の現金担当窓口では、証券の購入を担当することはない。

3. モデルを設計する
データの加工や検索、並び替えは、全てモデルで行う。コントローラにわざわざorderと記述するのは、よほどの個別事情の時のみ。

**Comment by ryokky59** [comment]
たくさんのコードレビューありがとうございます！
新しい発見ばかりで大変参考になります！

このイシューに関して質問です。

> users/:id のURLなのに、followersやschedulesが表示されるのは変。

`users/:id`には**ユーザー**がお気に入りしたスケジュールや**ユーザー**がフォローした、されたユーザーたちのページを**Ajax**の非同期通信で出したいため、URLが`users/:id`のままで実装しています。
メインコンテンツはそれぞれのユーザーのマイページなので、整合は取れているのかなあと感じました。

それとも**Ajax**を使わずにリクエストを送って、お気に入りしたスケジュール、フォローした、されたユーザーなどのページに飛ぶようにしたほうがいいのでしょうか？

**Comment by norotime** [comment]
@ryokky59 URLの設計上の観点では、別々にURLを切って作成した方が良い、ですね。
画面をごっちゃにするのもコンテンツの量的に、現実的に限界があると思います。facebookのURLもぜひご参考に〜。

**Comment by norotime** [comment]
@ryokky59 Ajaxがいけない、のではなくて、URLとその画面の設計の話です。ビューのディレクトリも分けた方が良いと思います。
